In [40]:
import numpy as np;

1. Create a rank 2 (2D) array that resembles the matrix below.
[[11 12 13 14]
 [15 16 17 18]]

In [41]:
myArray=np.array([[11, 12, 13, 14], [15, 16, 17, 18]]);
print(myArray);

[[11 12 13 14]
 [15 16 17 18]]


1. Create an array with 4 rows and 3 columns of zeros. Your results should look as below:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
myArray=np.zeros((4, 4));
print(myArray);



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2.Create an array of ones that has 3 rows and 4 columns. Your results should look as below:
[[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]]

In [43]:
myArray=np.ones((3, 4));
print(myArray);


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Create an array containing integers 4 to 13 inclusive. Your results should look as below:
[4 5 6 7 8 9 10 11 12 13]

In [44]:
myArray=np.arange(3, 14);
print(myArray);

[ 3  4  5  6  7  8  9 10 11 12 13]


4. Create an array containing
[0., 1.5, 3., 4.5]


In [45]:
myArray=np.linspace(0, 4.5, 4);
print(myArray);

[0.  1.5 3.  4.5]


5. Create a 2 by 2 array containing '4' in each position. Your results should look like this:
[[4 4]
 [4 4]]

In [46]:
myArray=np.full((2, 2), 4);
print(myArray);

[[4 4]
 [4 4]]


i. Identity matrix of size 4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
ii. Diagonal matrix with [10,12] as the diagonals
[[10  0]
 [ 0 12]]

In [47]:
myArray=np.eye(4)
print(myArray);
myArray=np.diag([10, 12])
print(myArray);

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0]
 [ 0 12]]


7. Create a 3 by 3 array with random floats in [0, 10]. Your answer may be different because it is random but it should look something like this:
[[6.3685612  0.61720883 8.93157783]
 [3.69927617 5.79879583 7.62145626]
 [7.21895112 4.02011535 4.48844787]]

In [48]:
myArray=np.random.random((3,3))*10;
print(myArray);

[[6.79381531 3.87588334 5.03146874]
 [9.73155747 7.28004937 1.097365  ]
 [4.15645867 6.85248804 9.36929667]]


8. Create a 3 by 3 array with random integers in [10, 20]. Your answer may be different because it is random but it should look something like this:
[[19 11 13]
 [10 11 13]
 [11 14 10]]

In [49]:
myArray=np.random.randint(10, 20, (3, 3));
print(myArray);

[[15 16 15]
 [19 14 15]
 [12 12 16]]


1. Use this array for the following practice:

In [50]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])


a. Get a subarray of the first row and first 2 columns. Your results should look like this:
[11 12]


In [54]:

print(myArray[0, 0:2]);

[11 12]


b. Change all elements in 1st and second row to 0. Your results should look like this:
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]
 

In [56]:
myArray[0:2, 0:]=0;
print(myArray);

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


2. Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.

In [66]:
myArray=np.arange(0, 21);
print(myArray[::-1]);

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


RESHAPING
Use this array for the following practice:

In [68]:
myArray = np.array([[11,12,13], [14,15,16]])

Reshape the array to an array with 3 rows. Your results should look like this:
[[11 12]
 [13 14]
 [15 16]]


In [70]:

print(myArray.reshape((3, 2)));

[[11 12]
 [13 14]
 [15 16]]


MATH
Use this array for the following practice:
myArray = np.arange(10)
1. Find the square of every number in array
2. Find the square root of every number in array
3. Multiply the square of each number in array with its respective square root

In [73]:
myArray = np.arange(10)
for(i) in myArray:
    myArray[i]=myArray[i]*myArray[i];
print(myArray);
myArray = np.arange(10)
for(i) in myArray:
    myArray[i]=np.sqrt(myArray[i]);
print(myArray);
myArray = np.arange(10)
for(i) in myArray:
    myArray[i]=np.sqrt(myArray[i])*np.exp2(myArray[i]);
print(myArray);  

[ 0  1  4  9 16 25 36 49 64 81]
[0 1 1 1 2 2 2 2 2 3]
[   0    2    5   13   32   71  156  338  724 1536]
